env:
  node: true
  es2021: true
  jest: true   # <-- agrega esta línea

extends: eslint:recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: off
  no-unused-vars: warn
  semi: ["error", "always"]
  quotes: ["error", "single"]
